# Generated by Django 5.1.5 on 2025-02-03 00:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(default=uuid.UUID('9d24f3dc-263b-42df-9fb0-8da7145597ed'), editable=False, unique=True),
        ),
    ]
