# Generated by Django 5.1.5 on 2025-02-03 01:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_auth_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(default=uuid.UUID('8a8f641d-6577-4f2f-b730-3481528123e3'), editable=False, unique=True),
        ),
    ]
