# Generated by Django 5.1.5 on 2025-02-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reservation_id_alter_room_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_token',
            field=models.UUIDField(),
        ),
    ]
